algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2023
// Seção de Declarações 
var
    n1, n2, soma: inteiro
    media: real
inicio
      escreva("Informe um número: ")
      leia(n1)
      escreva("Informe outro número: ")
      leia(n2)
      soma <- n1 + n2
      media <- (n1 + n2) / 2
      escreval("A soma de", n1, " e", n2, " é igual a ", soma)
      escreva("E a media deles é: ", media)
fimalgoritmo
